/**
 * @fileoverview gRPC-Web generated client stub for BitcoinInfo
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v4.24.1
// source: bitcoin_info.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as bitcoin_info_pb from './bitcoin_info_pb';


export class SearchPriceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetPrices = new grpcWeb.MethodDescriptor(
    '/BitcoinInfo.SearchPrice/GetPrices',
    grpcWeb.MethodType.UNARY,
    bitcoin_info_pb.PriceRequest,
    bitcoin_info_pb.Prices,
    (request: bitcoin_info_pb.PriceRequest) => {
      return request.serializeBinary();
    },
    bitcoin_info_pb.Prices.deserializeBinary
  );

  getPrices(
    request: bitcoin_info_pb.PriceRequest,
    metadata: grpcWeb.Metadata | null): Promise<bitcoin_info_pb.Prices>;

  getPrices(
    request: bitcoin_info_pb.PriceRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: bitcoin_info_pb.Prices) => void): grpcWeb.ClientReadableStream<bitcoin_info_pb.Prices>;

  getPrices(
    request: bitcoin_info_pb.PriceRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: bitcoin_info_pb.Prices) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/BitcoinInfo.SearchPrice/GetPrices',
        request,
        metadata || {},
        this.methodDescriptorGetPrices,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/BitcoinInfo.SearchPrice/GetPrices',
    request,
    metadata || {},
    this.methodDescriptorGetPrices);
  }

}

