/**
 * @fileoverview gRPC-Web generated client stub for BitcoinInfo
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v4.24.1
// source: bitcoin_info.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.BitcoinInfo = require('./bitcoin_info_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.BitcoinInfo.SearchPriceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.BitcoinInfo.SearchPricePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.BitcoinInfo.PriceRequest,
 *   !proto.BitcoinInfo.Prices>}
 */
const methodDescriptor_SearchPrice_GetPrices = new grpc.web.MethodDescriptor(
  '/BitcoinInfo.SearchPrice/GetPrices',
  grpc.web.MethodType.UNARY,
  proto.BitcoinInfo.PriceRequest,
  proto.BitcoinInfo.Prices,
  /**
   * @param {!proto.BitcoinInfo.PriceRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.BitcoinInfo.Prices.deserializeBinary
);


/**
 * @param {!proto.BitcoinInfo.PriceRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.BitcoinInfo.Prices)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.BitcoinInfo.Prices>|undefined}
 *     The XHR Node Readable Stream
 */
proto.BitcoinInfo.SearchPriceClient.prototype.getPrices =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/BitcoinInfo.SearchPrice/GetPrices',
      request,
      metadata || {},
      methodDescriptor_SearchPrice_GetPrices,
      callback);
};


/**
 * @param {!proto.BitcoinInfo.PriceRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.BitcoinInfo.Prices>}
 *     Promise that resolves to the response
 */
proto.BitcoinInfo.SearchPricePromiseClient.prototype.getPrices =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/BitcoinInfo.SearchPrice/GetPrices',
      request,
      metadata || {},
      methodDescriptor_SearchPrice_GetPrices);
};


module.exports = proto.BitcoinInfo;

