# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: bitcoin_info.proto for package 'BitcoinInfo'

require 'grpc'
require_relative 'bitcoin_info_pb'

module BitcoinInfo
  module SearchPrice
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'BitcoinInfo.SearchPrice'

      rpc :GetPrices, ::BitcoinInfo::PriceRequest, ::BitcoinInfo::Prices
    end

    Stub = Service.rpc_stub_class
  end
end
