version: '3'
services:
  db:
    image: postgres:15.3
    container_name: "bitcoin_rails_api_db"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./data:/var/lib/postgresql/data
    

  redis:
    image: redis:7.0.12
    container_name: "bitcoin_rails_api_redis"

  backend:
    build:
      context: ./backend
      dockerfile: rails.Dockerfile
    command: >
      bash -c "bundle exec rails db:setup DISABLE_DATABASE_ENVIRONMENT_CHECK=1 &&
      rm -f tmp/pids/server.pid && 
      bundle exec rails s -d -e production -p 3000 -b '0.0.0.0' &&
      bundle exec sidekiq -e production"
    # tty: true
    container_name: "bitcoin_rails_api_web"
    environment:
      RAILS_ENV: production
    volumes:
      - ./backend:/home/dev-user/backend
    expose:
      - "3000"
    depends_on:
      - db
      - redis
    user: dev-user

  frontend:
    build:
      context: ./frontend
      dockerfile: react.Dockerfile
    command: bash -c "npm run build && npm run start"
    tty: true
    container_name: "bitcoin_react_web"
    volumes:
      - ./frontend:/home/dev-user/frontend
    expose:
      - "4000"
    depends_on:
      - backend
    # user: dev-user

  nginx:
    image: nginx:1.25.1
    container_name: "bitcoin_nginx"
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
    # environment:
    #   - NGINX_PORT=5000
      #  - NGINX_HOST=foobar.com